# Auth Service - Development with H2
spring.datasource.url=jdbc:h2:mem:auth_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mailtrap SMTP (MFA OTP par email)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=3706f0418344b5
spring.mail.password=8bb0aa85fbd790
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# MFA OTP : expiration 5 min, max 5 tentatives, nettoyage toutes les 5 min
app.mfa.otp-validity-minutes=5
app.mfa.max-attempts=5
app.mfa.cleanup-cron=0 */5 * * * *
