server.port=8087
spring.application.name=admin-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
app.jwt.secret=${JWT_SECRET:dGhpcyBpcyBhIDI1Ni1iaXQgc2VjcmV0IGtleSBmb3Igand0IHRlc3Rpbmc=}
management.endpoints.web.exposure.include=health,info,prometheus,metrics
