server.port=8089
spring.application.name=conges-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
app.jwt.secret=dGhpcyBpcyBhIDI1Ni1iaXQgc2VjcmV0IGtleSBmb3Igand0IHRlc3Rpbmc=
management.endpoints.web.exposure.include=health,info,prometheus,metrics

# Jours fériés Maroc (Nager.Date)
app.nager.country=${NAGER_COUNTRY:MA}
# Cron acquisition mensuelle : 1er jour du mois à 01:00
app.conges.acquisition.cron=0 0 1 * * ?
